preserve_hierarchy: true
files:
  - source: /config/locales/en/*.yml
    translation: /config/locales/%two_letters_code%/%original_file_name%
    skip_untranslated_strings: true
  - source: /app/frontend/translations/en/*.js
    translation: /app/frontend/translations/%two_letters_code%/%original_file_name%
    skip_untranslated_strings: true
