version: 2.0

defaults: &defaults
  working_directory: ~/api
  docker:
    - image: fleetyards/api:2.5.1
      environment:
        RAILS_ENV: test
        DATABASE_HOST: 127.0.0.1
        DATABASE_USER: root
        LC_ALL: C.UTF-8
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
    - image: circleci/postgres:9.6.2-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: fleetyards_test

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/api
          paths:
            - ./
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/api

  bundle_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
      - run: bundle install --path vendor/bundle
      - persist_to_workspace:
          root: ~/api
          paths:
            - vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/api/vendor/bundle

  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api
      - run: bundle --path vendor/bundle
      - run:
          name: Update Audit DB
          command: bundle exec bundle-audit update
      - run:
          name: Check Audit DB
          command: bundle exec bundle-audit check

  rubocop:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api
      - run: bundle --path vendor/bundle
      - run:
          name: rubocoptering
          command: bundle exec rubocop --format progress

  seeds:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api
      - run: bundle --path vendor/bundle
      - run: bundle exec rails db:create db:schema:load
      - run:
          name: Run Seeds
          command: bundle exec rails db:seed

  unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api
      - run: bundle --path vendor/bundle
      - run: bundle exec rails db:create db:schema:load
      - run:
          name: Run Unit Tests
          command: bundle exec rails test
      - store_test_results:
          path: test/reports

  precompile_assets:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-assets-{{ .Environment.CIRCLE_SHA1 }}
            - v1-assets-
      - attach_workspace:
          at: ~/api
      - run: bundle --path vendor/bundle
      - run:
          name: Precompile assets
          command: bundle exec rails assets:precompile
      - persist_to_workspace:
          root: ~/api
          paths:
            - public/assets
      - save_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/api/public/assets

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api
      - run: bundle --path vendor/bundle
      - add_ssh_keys:
          fingerprints:
            - "b9:00:09:c3:96:48:ed:1e:90:c1:03:bc:3c:7d:14:59"
      - run:
          name: Keyscan Erelas (HACK)
          command: ssh-keyscan -H erelas.mortik.xyz >> ~/.ssh/known_hosts
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: bundle exec mina live deploy

workflows:
  version: 2
  check:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only: master
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - audit:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
      - seeds:
          requires:
            - bundle_dependencies
      - unit_tests:
          requires:
            - bundle_dependencies
      - precompile_assets:
          requires:
            - bundle_dependencies
  ci:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - audit:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
      - seeds:
          requires:
            - bundle_dependencies
      - unit_tests:
          requires:
            - bundle_dependencies
      - precompile_assets:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - audit
            - rubocop
            - seeds
            - unit_tests
            - precompile_assets
          filters:
            branches:
              only: master
