version: 2.0

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: fleetyards/app:2.5.1
      environment:
        RAILS_ENV: test
        DATABASE_HOST: 127.0.0.1
        DATABASE_USER: root
        LC_ALL: C.UTF-8
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
    - image: circleci/postgres:9.6.2-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: fleetyards_test

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  bundle_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
      - run: bundle install --path vendor/bundle
      - persist_to_workspace:
          root: ~/app
          paths:
            - vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle

  yarn_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}
            - v1-yarn-
      - run: yarn install
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/app/node_modules

  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run:
          name: Update Audit DB
          command: bundle exec bundle-audit update
      - run:
          name: Check Audit DB
          command: bundle exec bundle-audit check

  rubocop:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run:
          name: rubocoptering
          command: bundle exec rubocop --format progress

  eslint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: eslint
          command: yarn run lint

  seeds:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run: bundle exec rails db:create db:schema:load
      - run:
          name: Run Seeds
          command: bundle exec rails db:seed

  unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run: bundle exec rails db:create db:schema:load
      - run:
          name: Run Unit Tests
          command: bundle exec rails test
      - store_test_results:
          path: test/reports

  javascript_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: yarn install
      - run:
          name: Run Javascript Tests
          command: yarn test

  precompile_assets:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-assets-{{ .Environment.CIRCLE_SHA1 }}
            - v1-assets-
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run:
          name: Precompile assets
          command: bundle exec rails assets:precompile
      - persist_to_workspace:
          root: ~/app
          paths:
            - public/assets
      - save_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app/public/assets

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - add_ssh_keys:
          fingerprints:
            - "b9:00:09:c3:96:48:ed:1e:90:c1:03:bc:3c:7d:14:59"
      - run:
          name: Keyscan Erelas (HACK)
          command: ssh-keyscan -H erelas.mortik.xyz >> ~/.ssh/known_hosts
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: bundle exec mina live deploy

workflows:
  version: 2
  check:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only: master
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - yarn_dependencies:
          requires:
            - checkout_code
      - audit:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
      - eslint:
          requires:
            - yarn_dependencies
      - seeds:
          requires:
            - bundle_dependencies
      - unit_tests:
          requires:
            - bundle_dependencies
      - javascript_tests:
          requires:
            - yarn_dependencies
      - precompile_assets:
          requires:
            - bundle_dependencies
  main:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - bundle_dependencies:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - yarn_dependencies:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - audit:
          requires:
            - bundle_dependencies
          filters:
            tags:
              only: /.*/
      - rubocop:
          requires:
            - bundle_dependencies
          filters:
            tags:
              only: /.*/
      - eslint:
          requires:
            - yarn_dependencies
          filters:
            tags:
              only: /.*/
      - seeds:
          requires:
            - bundle_dependencies
          filters:
            tags:
              only: /.*/
      - unit_tests:
          requires:
            - bundle_dependencies
            - yarn_dependencies
          filters:
            tags:
              only: /.*/
      - javascript_tests:
          requires:
            - yarn_dependencies
          filters:
            tags:
              only: /.*/
      - precompile_assets:
          requires:
            - bundle_dependencies
            - yarn_dependencies
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - audit
            - rubocop
            - eslint
            - seeds
            - unit_tests
            - javascript_tests
            - precompile_assets
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
