version: 2.0

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: fleetyards/base:2.6.2
      environment:
        RAILS_ENV: test
        DATABASE_URL: postgresql://root:root@127.0.0.1:5432/fleetyards_test
        DATABASE_HOST: 127.0.0.1
        DATABASE_USER: root
        LC_ALL: C.UTF-8
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
    - image: circleci/postgres:9.5.16-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: fleetyards_test

e2e: &e2e
  working_directory: ~/app
  docker:
    - image: fleetyards/ci:2.6.2
      environment:
        DATABASE_URL: postgresql://root:root@127.0.0.1:5432/fleetyards
        TEST_SEEDS: 1
        RAILS_ENV: ci
        RAILS_SERVE_STATIC_FILES: 1
        DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
        CYPRESS_BASE_URL: http://localhost:8270
        CYPRESS_CI: 1
        APP_DIR: .
        PORT: 8270
        LC_ALL: C.UTF-8
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
    - image: circleci/postgres:9.5.16-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: fleetyards
    - image: circleci/redis:5.0.3-alpine

jobs:
  checkout-code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  bundle:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
      - run: bundle install --path vendor/bundle
      - persist_to_workspace:
          root: ~/app
          paths:
            - vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle

  yarn:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}
            - v1-yarn-
      - run: yarn install
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/app/node_modules

  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run:
          name: Update Audit DB
          command: bundle exec bundle-audit update
      - run:
          name: Check Audit DB
          command: bundle exec bundle-audit check

  rubocop:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run:
          name: rubocoptering
          command: bundle exec rubocop --format progress

  eslint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: eslint
          command: yarn run lint

  seeds:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run: bundle exec rails db:create db:schema:load
      - run:
          name: Run Seeds
          command: bundle exec rails db:seed

  ruby-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run: bundle exec rails db:create db:schema:load
      - run:
          name: Run Unit Tests
          command: bundle exec rails test
      - store_test_results:
          path: ~/app/test/reports

  js-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: yarn install
      - run:
          name: Run Javascript Tests
          command: yarn test

  build:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-assets-{{ .Environment.CIRCLE_SHA1 }}
            - v1-assets-
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run:
          name: Webpacker & Assets Compile
          command: RAILS_ENV=production bundle exec thor assets:compile
      - persist_to_workspace:
          root: ~/app
          paths:
            - public/assets
      - save_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app/public/assets

  e2e-tests:
    <<: *e2e
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - run: yarn install
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load
      - run:
          name: Webpacker & Assets Compile
          command: bundle exec thor assets:compile
      - run:
          name: Prefill DB
          command: bundle exec rails db:seed
      - run: mkdir -p tmp/pids && rm -f tmp/pids/*
      - run:
          name: Run Server
          command: bundle exec puma -C config/puma.rb
          background: true
      - run:
          name: Wait for Server
          command: |
              until $(curl --output /dev/null --silent --head --fail $CYPRESS_BASE_URL); do
                  printf '.'
                  sleep 5
              done
      - run: yarn install
      - run:
          name: Run E2E Tests
          command: yarn run test:e2e --record
      - store_artifacts:
          path: ~/app/cypress/snapshots
          destination: e2e-snapshots
      - store_artifacts:
          path: ~/app/cypress/screenshots
          destination: e2e-screenshots

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle --path vendor/bundle
      - add_ssh_keys:
          fingerprints:
            - "b9:00:09:c3:96:48:ed:1e:90:c1:03:bc:3c:7d:14:59"
      - run:
          name: Keyscan Erelas (HACK)
          command: ssh-keyscan -H erelas.mortik.xyz >> ~/.ssh/known_hosts
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: bundle exec mina live deploy

workflows:
  version: 2
  check:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only: master
    jobs:
      - checkout-code
      - bundle:
          requires:
            - checkout-code
      - yarn:
          requires:
            - checkout-code
      - audit:
          requires:
            - bundle
      - rubocop:
          requires:
            - bundle
      - eslint:
          requires:
            - yarn
      - seeds:
          requires:
            - bundle
      - ruby-tests:
          requires:
            - bundle
            - yarn
      - js-tests:
          requires:
            - yarn
      - build:
          requires:
            - bundle
            - yarn
      - e2e-tests:
          requires:
            - bundle
            - yarn
  main:
    jobs:
      - checkout-code
      - bundle:
          requires:
            - checkout-code
      - yarn:
          requires:
            - checkout-code
      - audit:
          requires:
            - bundle
      - rubocop:
          requires:
            - bundle
      - eslint:
          requires:
            - yarn
      - seeds:
          requires:
            - bundle
      - ruby-tests:
          requires:
            - bundle
            - yarn
      - js-tests:
          requires:
            - yarn
      - build:
          requires:
            - bundle
            - yarn
      - e2e-tests:
          requires:
            - bundle
            - yarn
      - deploy:
          requires:
            - e2e-tests
            - audit
            - rubocop
            - eslint
            - seeds
            - ruby-tests
            - js-tests
            - build
          filters:
            branches:
              only: master
