default: &defaults
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "Fleetyards"
  ignore_errors:
      - ActiveRecord::RecordNotFound
      - ActionController::RoutingError

development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true

staging:
  <<: *defaults
  active: true
