production: &defaults
  user: <%= ENV["HTTP_BASIC_USER"] %>
  password: <%= ENV["HTTP_BASIC_PASSWORD"] %>

staging:
  <<: *defaults

ci:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
