production:
  adapter: redis
  url: <%=ENV['REDIS_URL']%>
  channel_prefix: fleetyards_production

docker:
  adapter: redis
  url: <%=ENV['REDIS_URL']%>

development:
  adapter: redis
  url: <%=ENV['REDIS_URL']%>

test:
  adapter: test
