production:
  url: <%= ENV["DATABASE_URL"] %>

development:
  database: fleetyards_dev
  adapter: postgresql
  host: localhost

test:
  database: fleetyards_test
  adapter: postgresql
  host: localhost
