production:
  url: <%= ENV["DATABASE_URL"] %>

docker:
  url: <%= ENV["DATABASE_URL"] %>

development:
  database: fleetyards_dev
  adapter: postgresql
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  database: fleetyards_test
  adapter: postgresql
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
