production: &defaults
  url: <%= ENV["REDIS_URL"] || 'redis://localhost:6379' %>
  db: <%= ENV["REDIS_DB"] || 0 %>

staging:
  <<: *defaults

ci:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
