# see https://crontab.guru for help/explanation of cron lines

production: &production
  models_worker_job:
    cron: '*/10 * * * *'
    class: 'ModelsWorker'
  roadmap_worker_job:
    cron: '0 */1 * * *'
    class: 'RoadmapWorker'
  citizen_worker_job:
    cron: '0 */2 * * *'
    class: 'CitizenWorker'
  fleets_worker_job:
    cron: '0 1 * * *'
    class: 'FleetsWorker'
  cleanup_auth_tokens_worker:
    cron: '0 2 * * *'
    class: 'CleanupAuthTokensWorker'
  locations_worker_job:
    cron: '0 3 * * 0'
    class: 'LocationsWorker'
  admin_notifier_worker_job:
    cron: '0 20 * * 0'
    class: 'AdminNotifierWorker'
