# see https://crontab.guru for help/explanation of cron lines

production: &production
  ships_worker_job:
    cron: '0 * * * *'
    class: 'ShipsWorker'
  rsi_orgs_worker_job:
    cron: '30 * * * *'
    class: 'RsiOrgsWorker'
