# see https://crontab.guru for help/explanation of cron lines

production: &production
  models_worker_job:
    cron: '*/15 * * * *'
    class: 'ModelsWorker'
  fleets_worker_job:
    cron: '0 */2 * * *'
    class: 'FleetsWorker'
