production: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise: <%= ENV["DEVISE_SECRET"] %>
  google_analytics: <%= ENV["GOOGLE_ANALYTICS"] %>
  google_adsense: <%= ENV["GOOGLE_ADSENSE"] %>
  registration: true
  mailer_default_from: info@fleetyards.net
  mailer_admin_mail: admin@fleetyards.net
  mailer_host: <%= ENV["SMTP_HOST"] %>
  mailer_port: <%= ENV["SMTP_PORT"] %>
  mailer_user: <%= ENV["SMTP_USER"] %>
  mailer_password: <%= ENV["SMTP_PASSWORD"] %>
  domain: fleetyards.net
  rsi_hostname: https://robertsspaceindustries.com
  rsi_referral_code: <%= ENV["RSI_REFERRAL_CODE"] %>
  rsi_vat_percent: <%= ENV["RSI_VAT_PERCENT"] %>
  aws_key: <%= ENV["AWS_KEY"] %>
  aws_secret: <%= ENV["AWS_SECRET"] %>
  github_id: <%= ENV["GITHUB_OAUTH_ID"] %>
  github_secret: <%= ENV["GITHUB_OAUTH_SECRET"] %>
  facebook_id: <%= ENV["FACEBOOK_OAUTH_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_OAUTH_SECRET"] %>
  twitter_id: <%= ENV["TWITTER_OAUTH_ID"] %>
  twitter_secret: <%= ENV["TWITTER_OAUTH_SECRET"] %>
  google_id: <%= ENV["GOOGLE_OAUTH_ID"] %>
  google_secret: <%= ENV["GOOGLE_OAUTH_SECRET"] %>

development:
  <<: *default
  secret_key_base: development
  devise: development

test:
  <<: *default
  secret_key_base: test
  devise: test
