production: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "test" %>
  devise: <%= ENV["DEVISE_SECRET"] || "test" %>
  devise_jwt: <%= ENV["DEVISE_JWT_SECRET"] || '779a989560545187f66c9783dd837e4b9b7aa7051d3e6b34f35d3af313a129ab9fc33102c86f60771237fefc85b686d31c878e0b853d23f45e091b2528fb41bf' %>
  jwt_expiration: <%= 24.hours.to_i %>
  devise_otp_issuer: FleetYards.net
  mailer_default_from: "FleetYards.net <info@fleetyards.net>"
  mailer_admin_mail: "FleetYards.net Admin <admin@fleetyards.net>"
  mailer_host: <%= ENV["SMTP_HOST"] %>
  mailer_port: <%= ENV["SMTP_PORT"] %>
  mailer_user: <%= ENV["SMTP_USER"] %>
  mailer_password: <%= ENV["SMTP_PASSWORD"] %>
  store_version: <%= ENV["STORE_VERSION"] || 8 %>
  embed_store_version: <%= ENV["EMBED_STORE_VERSION"] || 1 %>
  domain: <%= ENV["DOMAIN"] || 'fleetyards.net' %>
  frontend_endpoint: <%= ENV["FRONTEND_ENDPOINT"] || 'https://fleetyards.net' %>
  api_endpoint: <%= ENV["API_ENDPOINT"] || 'https://api.fleetyards.net/v1' %>
  admin_api_endpoint: <%= ENV["ADMIN_API_ENDPOINT"] || 'https://admin.fleetyards.net/api/v1' %>
  rsi_endpoint: <%= ENV["RSI_ENDPOINT"] || 'https://robertsspaceindustries.com' %>
  cable_endpoint: <%= ENV["CABLE_ENDPOINT"] || 'wss://api.fleetyards.net/cable' %>
  rsi_vat_percent: <%= ENV["RSI_VAT_PERCENT"] || 0 %>
  sentry_frontend_dsn: https://08098ede002640439a5e79b9732984fc@sentry.io/124907

development:
  <<: *default
  domain: <%= ENV["DOMAIN"] || 'fleetyards.test' %>
  frontend_endpoint: http://fleetyards.test
  api_endpoint: http://api.fleetyards.test/v1
  admin_api_endpoint: http://admin.fleetyards.test/api/v1
  cable_endpoint: ws://api.fleetyards.test/cable

ci:
  <<: *default
  frontend_endpoint: http://localhost:8270
  api_endpoint: http://localhost:8270/api/v1
  admin_api_endpoint: http://localhost:8270/admin/api/v1
  cable_endpoint: ws://localhost:8270/cable

test:
  <<: *default
  frontend_endpoint: http://localhost:8270
  api_endpoint: http://localhost:8270/api/v1
  admin_api_endpoint: http://localhost:8270/admin/api/v1
  cable_endpoint: ws://localhost:8270/cable
