development:
  secret_key_base: development
  devise: development
  google_analytics:
  base:
    registration: true
  mailer:
    default_from: info@fleetyards.net
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  domain: fleetyards.net
  rsi_hostname: https://robertsspaceindustries.com
  rsi_referral_code: foo123
  aws:
    key: <%= ENV["AWS_KEY"] %>
    secret: <%= ENV["AWS_SECRET"] %>
  github:
    id: <%= ENV["GITHUB_OAUTH_ID"] %>
    secret: <%= ENV["GITHUB_OAUTH_SECRET"] %>
  facebook:
    id: <%= ENV["FACEBOOK_OAUTH_ID"] %>
    secret: <%= ENV["FACEBOOK_OAUTH_SECRET"] %>
  twitter:
    id: <%= ENV["TWITTER_OAUTH_ID"] %>
    secret: <%= ENV["TWITTER_OAUTH_SECRET"] %>
  google:
    id: <%= ENV["GOOGLE_OAUTH_ID"] %>
    secret: <%= ENV["GOOGLE_OAUTH_SECRET"] %>

test:
  secret_key_base: test
  devise: test
  google_analytics:
  base:
    registration: true
  mailer:
    default_from: info@fleetyards.net
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  domain: fleetyards.net
  rsi_hostname: https://robertsspaceindustries.com
  rsi_referral_code: <%= ENV["RSI_REFERRAL_CODE"] %>
  aws:
    key: <%= ENV["AWS_KEY"] %>
    secret: <%= ENV["AWS_SECRET"] %>
  github:
    id: <%= ENV["GITHUB_OAUTH_ID"] %>
    secret: <%= ENV["GITHUB_OAUTH_SECRET"] %>
  facebook:
    id: <%= ENV["FACEBOOK_OAUTH_ID"] %>
    secret: <%= ENV["FACEBOOK_OAUTH_SECRET"] %>
  twitter:
    id: <%= ENV["TWITTER_OAUTH_ID"] %>
    secret: <%= ENV["TWITTER_OAUTH_SECRET"] %>
  google:
    id: <%= ENV["GOOGLE_OAUTH_ID"] %>
    secret: <%= ENV["GOOGLE_OAUTH_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise: <%= ENV["DEVISE_SECRET"] %>
  google_analytics: <%= ENV["GOOGLE_ANALYTICS"] %>
  base:
    registration: true
  mailer:
    default_from: info@fleetyards.net
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  domain: fleetyards.net
  rsi_hostname: https://robertsspaceindustries.com
  rsi_referral_code: <%= ENV["RSI_REFERRAL_CODE"] %>
  aws:
    key: <%= ENV["AWS_KEY"] %>
    secret: <%= ENV["AWS_SECRET"] %>
  github:
    id: <%= ENV["GITHUB_OAUTH_ID"] %>
    secret: <%= ENV["GITHUB_OAUTH_SECRET"] %>
  facebook:
    id: <%= ENV["FACEBOOK_OAUTH_ID"] %>
    secret: <%= ENV["FACEBOOK_OAUTH_SECRET"] %>
  twitter:
    id: <%= ENV["TWITTER_OAUTH_ID"] %>
    secret: <%= ENV["TWITTER_OAUTH_SECRET"] %>
  google:
    id: <%= ENV["GOOGLE_OAUTH_ID"] %>
    secret: <%= ENV["GOOGLE_OAUTH_SECRET"] %>
