production: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "test" %>
  devise: <%= ENV["DEVISE_SECRET"] || "test" %>
  devise_jwt: <%= ENV["DEVISE_JWT_SECRET"] || '779a989560545187f66c9783dd837e4b9b7aa7051d3e6b34f35d3af313a129ab9fc33102c86f60771237fefc85b686d31c878e0b853d23f45e091b2528fb41bf' %>
  jwt_expiration: <%= 24.hours.to_i %>
  google_analytics: <%= ENV["GOOGLE_ANALYTICS"] %>
  registration: true
  mailer_default_from: "FleetYards.net <info@fleetyards.net>"
  mailer_admin_mail: "FleetYards.net Admin <admin@fleetyards.net>"
  mailer_host: <%= ENV["SMTP_HOST"] %>
  mailer_port: <%= ENV["SMTP_PORT"] %>
  mailer_user: <%= ENV["SMTP_USER"] %>
  mailer_password: <%= ENV["SMTP_PASSWORD"] %>
  domain: fleetyards.net
  rsi_hostname: https://robertsspaceindustries.com
  rsi_referral_code: <%= ENV["RSI_REFERRAL_CODE"] %>
  rsi_vat_percent: <%= ENV["RSI_VAT_PERCENT"] %>
  aws_key: <%= ENV["AWS_KEY"] %>
  aws_secret: <%= ENV["AWS_SECRET"] %>
  github_id: <%= ENV["GITHUB_OAUTH_ID"] %>
  github_secret: <%= ENV["GITHUB_OAUTH_SECRET"] %>
  facebook_id: <%= ENV["FACEBOOK_OAUTH_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_OAUTH_SECRET"] %>
  twitter_id: <%= ENV["TWITTER_OAUTH_ID"] %>
  twitter_secret: <%= ENV["TWITTER_OAUTH_SECRET"] %>
  google_id: <%= ENV["GOOGLE_OAUTH_ID"] %>
  google_secret: <%= ENV["GOOGLE_OAUTH_SECRET"] %>

development:
  <<: *default

test:
  <<: *default
