production: &default
  app_name: <%= ENV["APP_NAME"] %>

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise: <%= ENV["DEVISE_SECRET"] %>

  devise_otp_issuer: <%= ENV["APP_NAME"] %>
  devise_otp: <%= ENV["DEVISE_OTP_SECRET"] %>
  devise_admin_otp: <%= ENV["DEVISE_ADMIN_OTP_SECRET"] %>

  confirm_access_secret: <%= ENV["CONFIRM_ACCESS_SECRET"] %>

  mailer_default_from: <%= ENV["MAILER_DEFAULT_FROM"] %>

  copyright_owner: <%= ENV["COPYRIGHT_OWNER"] %>

  maintainer_name: <%= ENV["MAINTAINER_NAME"] %>
  maintainer_mail: <%= ENV["MAINTAINER_MAIL"] %>
  maintainer_address_street: <%= ENV["MAINTAINER_ADDRESS_STREET"] %>
  maintainer_address_postalcode: <%= ENV["MAINTAINER_ADDRESS_POSTALCODE"] %>
  maintainer_address_city: <%= ENV["MAINTAINER_ADDRESS_CITY"] %>
  maintainer_address_country: <%= ENV["MAINTAINER_ADDRESS_COUNTRY"] %>

  admin_mail: <%= ENV["ADMIN_MAIL"] %>

  mailer_host: <%= ENV["SMTP_HOST"] %>
  mailer_port: <%= ENV["SMTP_PORT"] %>
  mailer_user: <%= ENV["SMTP_USER"] %>
  mailer_password: <%= ENV["SMTP_PASSWORD"] %>

  store_version: <%= ENV["STORE_VERSION"] || 10.3 %>
  embed_store_version: <%= ENV["EMBED_STORE_VERSION"] || 2.0 %>

  domain: <%= ENV["DOMAIN"] %>
  short_domain: <%= ENV["SHORT_DOMAIN"] %>
  cookie_domain: <%= ENV["COOKIE_DOMAIN"] %>
  cookie_prefix: <%= ENV["COOKIE_PREFIX"] %>

  frontend_endpoint: <%= ENV["FRONTEND_ENDPOINT"] %>
  api_endpoint: <%= ENV["API_ENDPOINT"] %>
  admin_api_endpoint: <%= ENV["ADMIN_API_ENDPOINT"] %>
  cable_endpoint: <%= ENV["CABLE_ENDPOINT"] %>

  rsi_endpoint: <%= ENV["RSI_ENDPOINT"] || 'https://robertsspaceindustries.com' %>
  rsi_vat_percent: <%= ENV["RSI_VAT_PERCENT"] || 0 %>

  sentry_dsn: <%= ENV["SENTRY_DSN"] %>
  sentry_frontend_dsn: <%= ENV["SENTRY_FRONTEND_DSN"] %>
  sentry_csp_uri: <%= ENV["SENTRY_CSP_URI"] %>

  carrierwave_cloud_key: <%= ENV["CARRIERWAVE_CLOUD_KEY"] %>
  carrierwave_cloud_secret: <%= ENV["CARRIERWAVE_CLOUD_SECRET"] %>
  carrierwave_cloud_region: <%= ENV["CARRIERWAVE_CLOUD_REGION"] %>
  carrierwave_cloud_endpoint: <%= ENV["CARRIERWAVE_CLOUD_ENDPOINT"] %>
  carrierwave_cloud_space: <%= ENV["CARRIERWAVE_CLOUD_SPACE"] %>
  carrierwave_cloud_cdn_endpoint: <%= ENV["CARRIERWAVE_CLOUD_CDN_ENDPOINT"] %>

  google_youtube_api_key: <%= ENV["GOOGLE_YOUTUBE_API_KEY"] %>

  discord_updates_endpoint: <%= ENV["DISCORD_UPDATES_ENDPOINT"] %>
  discord_sc_updates_endpoint: <%= ENV["DISCORD_SC_UPDATES_ENDPOINT"] %>
  discord_progress_tracker_updates_endpoint: <%= ENV["DISCORD_PROGRESS_TRACKER_UPDATES_ENDPOINT"] %>

  cors_origins:
    - <%= ENV["FRONTEND_ENDPOINT"] || 'localhost' %>
    - <%= ENV["ADMIN_ENDPOINT"] || 'localhost' %>

staging:
  <<: *default

ci:
  <<: *default

  secret_key_base: test
  devise: test
  devise_otp: 39c3eb3cea32862a51713a081d3a97b68a09b3169a9cae185d8dffeee0bd07229a267066e31627a46b2f87e4cc7a5c837d1de4fa6f0e482cf7a9a426f303bbfe
  devise_admin_otp: 8b477c4ca4e5835745426adebb35b98a62dd6afaabcaf22c700c61ef4ef077a4e67b449a22a3c17e04cad18f7bd1614fc0f35c77357ecaa5bb17fc47595b91dd
  confirm_access_secret: 2e9611ff6e45ac4e02055a2689cae200c617c26efecabbf207aee878bd81067a09beda629a824107cac36f9ef6cee4359dff2cf631d28c674a8fd317bef530e8

  domain: localhost:8270
  frontend_endpoint: http://localhost:8270
  api_endpoint: http://localhost:8270/api/v1
  admin_api_endpoint: http://localhost:8270/admin/api/v1
  cable_endpoint: ws://localhost:8270/cable
  sentry_dsn: https://763123f723e3482790f14e89ca1a9623@o58249.ingest.sentry.io/1401277
  sentry_frontend_dsn:
  cors_origins:
    - http://localhost:8270
  cookie_domain:

development:
  <<: *default

  secret_key_base: test
  devise: test
  devise_otp: 39c3eb3cea32862a51713a081d3a97b68a09b3169a9cae185d8dffeee0bd07229a267066e31627a46b2f87e4cc7a5c837d1de4fa6f0e482cf7a9a426f303bbfe
  devise_admin_otp: 8b477c4ca4e5835745426adebb35b98a62dd6afaabcaf22c700c61ef4ef077a4e67b449a22a3c17e04cad18f7bd1614fc0f35c77357ecaa5bb17fc47595b91dd
  confirm_access_secret: 2e9611ff6e45ac4e02055a2689cae200c617c26efecabbf207aee878bd81067a09beda629a824107cac36f9ef6cee4359dff2cf631d28c674a8fd317bef530e8

  domain: <%= ENV["DOMAIN"] || 'fleetyards.test' %>
  short_domain: <%= ENV["SHORT_DOMAIN"] || 'fltyrd.test' %>
  cookie_domain: '.fleetyards.test'
  cookie_prefix: 'FLTYRD_DEV'

  frontend_endpoint: http://fleetyards.test
  # frontend_endpoint: http://localhost:8270
  api_endpoint: http://api.fleetyards.test/v1
  # api_endpoint: http://localhost:8270/api/v1
  admin_api_endpoint: http://admin.fleetyards.test/api/v1
  cable_endpoint: ws://api.fleetyards.test/cable
  sentry_dsn:
  sentry_frontend_dsn:
  cors_origins:
    - http://localhost:8270
    - http://fleetyards.test
    - http://admin.fleetyards.test
  # cookie_domain:

test:
  <<: *default

  secret_key_base: test
  devise: test
  devise_otp: 39c3eb3cea32862a51713a081d3a97b68a09b3169a9cae185d8dffeee0bd07229a267066e31627a46b2f87e4cc7a5c837d1de4fa6f0e482cf7a9a426f303bbfe
  devise_admin_otp: 8b477c4ca4e5835745426adebb35b98a62dd6afaabcaf22c700c61ef4ef077a4e67b449a22a3c17e04cad18f7bd1614fc0f35c77357ecaa5bb17fc47595b91dd
  confirm_access_secret: 2e9611ff6e45ac4e02055a2689cae200c617c26efecabbf207aee878bd81067a09beda629a824107cac36f9ef6cee4359dff2cf631d28c674a8fd317bef530e8

  domain: <%= ENV["DOMAIN"] || 'fleetyards.test' %>
  frontend_endpoint: http://localhost:8270
  api_endpoint: http://localhost:8270/api/v1
  admin_api_endpoint: http://localhost:8270/admin/api/v1
  cable_endpoint: ws://localhost:8270/cable
  sentry_dsn:
  sentry_frontend_dsn:
  cors_origins:
    - http://localhost:8270
  cookie_domain:
