---
:queues:
  - fleetyards_model_loader
  - fleetyards_vehicles_loader
  - fleetyards_fleets_loader
  - fleetyards_location_loader
  - fleetyards_mailers
  - fleetyards_model_notification
  - fleetyards_cleanup_auth_tokens
  - fleetyards_app_version_notifications
