name: JS Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    container: fleetyards/base:2.6.6

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ~/app/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: js lint
        run: yarn lint:js

      - name: vue lint
        run: yarn lint:vue

      - name: stylelint
        run: yarn lint:style

      - name: tests
        run: yarn test:coverage
